---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Write up

### Data

The main sources of data in our project are two popular NBA stat websites: basketball-reference.com and espn.com.

In the data_scraping.R, firstly we scraped the Game Log of LeBron James (regular season, 2004-2019) and Kevin Durant (regular season, 2008-2019) from basketball-reference.com. Then we scraped both LeBron James's (2006-2018) and Kevin Durant's (2010-2014, 2016-2019) Playoffs Game Log. Next we get both players' shooting data during all the periods (regular season and Playoffs). At last we scraped both their regular season and playoff periods average data from espn.com. We saved the raw data in james_raw.rds and durant_raw.rds.

In the data_cleaning.R, we firstly built some helper functions (in general: to.na, time.to.num; for "average": split1, split2; for "shooting": shooting.clean; for Shiny: season.make) to help cleaning the data. We cleaned the regular season data by modifying column names, removing redundant data, dealing with missing data and formatting, and then repeated a similar process for the playoff data. Next we formatted the regular season/ playoffs average data correctly and cleaned the shooting data with missing values and non-numerics. We also tried to get records of face-to-face matches between James and Durant. At last, we got two lists of well structured data: james.rds and durant.rds. Each list has four main sub-lists (reg, shoot, playoff and avg). We will use these data to do analysis about the two players and visulize our results by tables and dynamic plots in a Shiny app.

The variables codebook of our data is as the following:
Date -- Date of Game
season -- Game Season
Series -- 
Tm/Team -- Team Name
Home -- Whether Play at Home
Opp -- Opponent
GP -- Games Played
GS -- Games Started
MIN -- Minutes Per Game
MP -- Minutes Played
FG -- Field Goals
FGA -- Field Goal Attempts
FG% -- Field Goal Percentage
3P -- 3-Point Field Goals
3PA -- 3-Point Field Goal Attempts
3P% -- 3-Point Field Goal Percentage
FT -- Free Throws
FTA -- Free Throw Attempts
FT% -- Free Throw Percentage
ORB/OR -- Offensive Rebounds
DRB/DR -- Defensive Rebounds
TRB/REB -- Total Rebounds
AST -- Assists
STL -- Steals
BLK -- Blocks
TOV/TO -- Turnovers
PF -- Personal Fouls
PTS -- Points
GmSc -- Game Score
+/- -- Plus/Minus
Res.w -- 
Res.diff --
Split -- Type of Splits
Value -- Record of Value
eFG% -- 
Ast'd -- 
%Ast'd -- 




